### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by satyendra22** [LimberDuck/nessus-file-analyzer#6]
When select "scan" and "host" report type then its thrown below error

  Traceback (most recent call last):
  File "C:\Satya\tools\nessus-file-analyzer\nessus_file_analyzer\app.py", line 1383, in create_worksheet_for_scans
    policy_max_hosts = int(nfr.scan.policy_max_hosts(root))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "C:\Satya\tools\nessus-file-analyzer\nessus_file_analyzer\app.py", line 1720, in create_worksheet_for_hosts
    policy_max_hosts = int(nfr.scan.policy_max_hosts(root))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by damian-krawczyk** [comment]
@satyendra22 do you still have this issue in the latest release, [v0.12.5](https://github.com/LimberDuck/nessus-file-reader/releases)￼?
